title: Kayla Musser
description: Driven and resourceful college student majoring in sociology with an interest in computer science applications for data analysis and market research. Experienced in introductory programming and data science, I bring a unique perspective on understanding social behavior and trends, which I use to inform engagement strategies. Passionate about leveraging technology to analyze complex datasets and apply sociological insights to optimize user engagement and marketing strategies. Currently seeking opportunities to combine my technical skills and sociological expertise in environments that emphasize data-driven solutions and impactful communication.
Contact: https://www.linkedin.com/mynetwork/grow/
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
